@PurchaseManagement.API_HostAddress = http://localhost:5241

GET {{PurchaseManagement.API_HostAddress}}/todos/
Accept: application/json

###

GET {{PurchaseManagement.API_HostAddress}}/todos/1
Accept: application/json

###

GET {{PurchaseManagement.API_HostAddress}}/todos/

###

GET {{PurchaseManagement.API_HostAddress}}/todos/1

###
