name: Build .NET MAUI Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: |
         cd PurchaseManagement
         dotnet build --configuration Release --no-restore
         echo 'build done'
